<?php defined('BASEPATH') OR exit('No direct script access allowed');?>
<script src="<?php echo $link_template;?>/js/jquery-1.12.1.min.js"></script>
<!-- popper js -->
<script src="<?php echo $link_template;?>/js/popper.min.js"></script>
<!-- bootstrap js -->
<script src="<?php echo $link_template;?>/js/bootstrap.min.js"></script>
<!-- easing js -->
<script src="<?php echo $link_template;?>/js/jquery.magnific-popup.js"></script>
<!-- swiper js -->
<script src="<?php echo $link_template;?>/js/swiper.min.js"></script>
<!-- swiper js -->
<script src="<?php echo $link_template;?>/js/masonry.pkgd.js"></script>
<!-- particles js -->
<script src="<?php echo $link_template;?>/js/owl.carousel.min.js"></script>
<script src="<?php echo $link_template;?>/js/jquery.nice-select.min.js"></script>
<!-- swiper js -->
<script src="<?php echo $link_template;?>/js/slick.min.js"></script>
<script src="<?php echo $link_template;?>/js/jquery.counterup.min.js"></script>
<script src="<?php echo $link_template;?>/js/waypoints.min.js"></script>
<!-- custom js -->
<script src="<?php echo $link_template;?>/js/custom.js"></script>